### ISSUE TITLE
typo for LICENSE.txt

### ISSUE THREAD

**Issue by skylinezum** [helium/helium-client-python#2]
name should be `LICENSE.txt` not `LICENCE.txt`

error when installing
```
error: [Errno 2] No such file or directory: 'LICENSE.txt'
```

https://github.com/helium/helium-client-python/blob/master/setup.py#L39

**Comment by madninja** [comment]
Thanks @skylinezum. I believe it's now fixed in https://github.com/helium/helium-client-python/commit/639f755ca88d4861d6f67e896dd93f5dc3637ad9
